url: ${RAILWAY_STATIC_URL}

# Port
port: ${PORT}

# PostgreSQL
db:
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  db: ${POSTGRES_DATABASE}
  user: ${POSTGRES_USER}
  pass: ${POSTGRES_PASSWORD}

# Redis
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  pass: ${REDIS_PASSWORD}
  prefix: misskey
  db: 0

# ID Generation
id: 'aid'

# UI Customization
name: 'My Misskey Instance'
description: 'Welcome to my Misskey instance!'
defaultLightTheme: l-rosepine
defaultDarkTheme: d-rosepine

# Disable unnecessary features
enableEmail: false
enableTwitterIntegration: false
enableGithubIntegration: false
enableDiscordIntegration: false
enableServiceWorker: false

# Menu customization
menu:
  home: true
  notifications: true
  messaging: false
  drive: true
  followRequests: false
  explore: true
  announcements: false
  search: true
  settings: true

# Security
disableHtml: true
disableRegistration: true
disableLocalTimeline: true
disableFederation: true
disableIndexing: true
disableGlobalTimeline: true
disableAiNickname: true
disableHsts: true
